version: "3.9"

services:
  gdc-ian-unsafe-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: gdc-ian-unsafe-api:latest
    container_name: gdc-ian-unsafe-api
    ports:
      - "80:80"
    env_file:
      - .env
    restart: unless-stopped

    # Voor dev: uncomment volumes zodat lokale code direct gebruikt wordt:
    # volumes:
    #   - ./app:/code/app